config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]

  root 'properties#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true, numericality: { greater_than: 0 }

  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    if end_date && start_date && end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :price_per_night, presence: true, numericality: { greater_than: 0 }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 10}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: user_id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @property = Property.find(params[:property_id])
    @booking = Booking.new
  end

  def create
    @property = Property.find(params[:property_id])
    @booking = @property.bookings.new(booking_params)
    @booking.user_id = user_id
    if @booking.save
      redirect_to @property
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
    @reviews = @property.reviews
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.user_id = current_user.id
    if @property.save
      redirect_to @property
    else
      render :new
    end
  end

  private

  def property_params
    params.require(:property).permit(:title, :description, :address, :city, :country, :price_per_night, :capacity)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @property = Property.find(params[:property_id])
    @review = @properties.reviews.new
  end
  
  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.new(review_params)
    @review.user_id = user_id
    if @review.save
      redirect_to @property
    else
      render 'properties/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookings/index.html.erb
<h1>Your Bookings</h1>

<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to "Booking ##{booking.id} at #{booking.property.title}", booking %>
    </li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<h1>New Booking for <%= @property.title %></h1>

<%= form_with model: [@property, @booking] do |form| %>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :total_price %>
    <%= form.number_field :total_price %>
  </div>

  <div>
    <%= form.submit 'Create Booking' %>
  </div>
<% end %>

<%= link_to 'Back to Property', property_path(@property) %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p>Property: <%= @booking.property.title %></p>
<p>Start Date: <%= @booking.start_date %></p>
<p>End Date: <%= @booking.end_date %></p>
<p>Total Price: <%= @booking.total_price %></p>

<%= link_to 'Back to Bookings', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAirBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/index.html.erb
<h1>Properties</h1>

<%= link_to 'New Property', new_property_path %>

<ul>
  <% @properties.each do |property| %>
    <li>
      <%= link_to property.title, property %>
    </li>
  <% end %>
</ul>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= form_with model: @property do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :price_per_night %>
    <%= form.text_field :price_per_night %>
  </div>

  <div>
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.submit 'Create Property' %>
  </div>
<% end %>

<%= link_to 'Back to Properties', properties_path %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @property.title %></h1>

<%= form_with model: [@property, @review] do |form| %>
  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit 'Submit Review' %>
  </div>
<% end %>

<%= link_to 'Back to Property', property_path(@property) %>